### ISSUE TITLE
Health bar

### ISSUE THREAD

**Issue by ekhalikar** [BoolClub/ProjectCrusade#19]
You can continue to add apples into the person even when the health bar is full.

**Comment by Authman2** [comment]
You can still eat apples, they just won't restore any health if it is already at 100.

**Comment by AnonymousNix** [comment]
This does not appear to be an issue. We cannot reasonably restrict the player from eating with full health, as some foods in the future may have other effects besides healing. (also, if you eat all your apples, that's your own fault. Don't be a glutton.)
If there are no objections, we may close this issue.
