### ISSUE TITLE
Entraces In Rooms

### ISSUE THREAD

**Issue by Authman2** [BoolClub/ProjectCrusade#39]
How many entry ways should each room have? I know they are being procedurally laid out, but the hallways need to connect to the entry ways so the player can actually go into the rooms. Should I just draw four entry ways into each room (top, bottom, left, right)?

**Comment by christiancosgrove** [comment]
Any number of entrances in any position should be fine. I've designed it so that any non-solid edge tiles connect to the hallways.

**Comment by Authman2** [comment]
Ok I'll try to design a lot of different kinds so that we can have some variety in the rooms.
