### ISSUE TITLE
Inventory screen

### ISSUE THREAD

**Issue by christiancosgrove** [BoolClub/ProjectCrusade#4]
We have to migrate the inventory to a new screen. As a GameScreen laying on top of the MainGameScreen, the main game will be paused when the inventory is fully open. However, we should add a special draw method to the inventory class that allows us to _just render the main row_. Each item on the main row will be indexed by a number key and will therefore be easily accessible in game.

**Comment by Authman2** [comment]
Ok, so we can start writing a new GameScreen for the inventory and that is what will be displayed when toggle is true. When toggle is false, then we can just draw that one row with indexed numbers. That way we can use the numbers on the keyboard to quick select something.
