### ISSUE TITLE
In-game layers

### ISSUE THREAD

**Issue by christiancosgrove** [BoolClub/ProjectCrusade#40]
Looking at the new tiles @Authman2 added, should we re-implement tile layers? This would be one of the only ways to have tile transparency. 

I might be able to implement culling for occluded tiles-i.e. if a "wall tile" is not transparent, don't render the tile behind it.

**Comment by Authman2** [comment]
I like the idea of not rendering tiles under it if the tile is not transparent, but if that is the case then I can just draw it accordingly in Tiled. Unless it is easier to organize with layers, or unless that is the only way to have transparency, I think it's ok if we don't have them.

**Comment by christiancosgrove** [comment]
Ok. So no layers for now. We have to add floor tiles in the background of the tent then. 

As for future levels using new tile families, we need to make sure we design each of the tiles included in the TileFamily class.

**Comment by christiancosgrove** [comment]
What I mean is that we won't have layers in game, but we can (and should) use layers in Tiled. Putting tiles on the "Wall" layer indicates that it will be solid in game.
