### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Authman2** [BoolClub/ProjectCrusade#47]
There is an error when trying to display the text box on the treasure chest. When you click on it after shooting an arrow, whether the arrow is currently selected or not, the treasure chest will not display the "received item" message. Sometimes it works, and other times it doesn't.

**Comment by Authman2** [comment]
UPDATE:
It changes. Sometimes it stops working after using the sword, other times it stops working after using the arrow.

**Comment by christiancosgrove** [comment]
I think I fixed it. The fix will be pushed to `master` when I merge the `magic-items` branch.
