### ISSUE TITLE
Use Wikis for documentation

### ISSUE THREAD

**Issue by christiancosgrove** [BoolClub/ProjectCrusade#5]
I think we should use Wikis from now on for documentation. We can transfer the information shared in those Google docs to the Wiki. That way, all members of the GitHub organization can access this information, consulting with it for development or editing it themselves. It supports multiple pages and formatting.

Plus, _when we do release the game_, it will be easy to make public.

**Comment by Authman2** [comment]
Sounds good. I'll start working on transferring everything now and then we'll just tell them to start using this one instead of the google doc.
